[package]
name = "schema"
version = "0.1.0"
authors = ["Dan Murphy <danhatesnumbers@gmail.com"]

[dependencies]
clap = "2"
valico = { git = "https://github.com/korczis/valico", branch = "serde-1.0" }
serde = "1"
serde_json = "1"